//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Soft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Table()
        {
            this.Student_Table = new HashSet<Student_Table>();
        }
    
        public string Course_Title { get; set; }
        public string Course_ID { get; set; }
        public string Class_Detail { get; set; }
        public string Class_Detail2 { get; set; }
        public string Class_Detail3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Table> Student_Table { get; set; }
    }
}
